"""
Problem generated by ChatGPT
Problem 1 — Peak Detection (1D)

Title: NMRP1

Given:
A list of intensity values representing a 1D NMR spectrum:

S = [s₀, s₁, ..., sₙ]

Task:
Return the indices of all local maxima, where:

s[i] > s[i-1] and s[i] > s[i+1]

Return:
A list of indices.

Example:

Input:
[0, 2, 5, 3, 1, 4, 6, 2]

Output:
[2, 6]

"""

S = [0, 2, 5, 3, 1, 4, 6, 2]
max = []

for i in range(1,len(S)):
    if S[i] > S[i-1] and S[i] > S[i+1]:
        max.append(S[i])

with open("NMRP1_output.txt", 'w+') as f:
    # write elements of list
    for items in max:
        f.write('%s ' %items)