string = "TGCCACTACTGGGATCCCCAGCCCTTTTTACTGTCCACCACCCTCCCCCAAAGGGGGCCACTGCACCAGACCCGAAAAAAAACAAAGGTGAGGCATCCACGGACCTTTTGATAATCAGGTCTGGATAATCTCTGGTGCTCTACGACGGCCTGAAGGATGTTTTTGAATCACGTCGAGGGTAGAGTTCTCGCGTCGACCTATCCTAAAGGAAAGACTTTGGTCTACTGTGGTACTCGAATCCGAGCGTACAAAGGTGTAGGGTATGTCATGTTAGTGTCCTTCGTGAACTCGCCCACCGACTGTCCGATAAGTATTGGCCCCAGAAGGGGCAGGACAAGAGTGAATGTGACAACAAACATTATGTTCGTGGCTAACGTATGTCTGAGTAAGATTAGAGGAAGCTCTTTATGCACGTTTAGGGCTCAGAGACTATAAGTATTGGTATGCTAAGCAGGACTAGATCTGTCTTTCGTACCTCCCGAGTGCCGTTTATGGACCGAATCTAAGTAGCACTTAAAGGGTAGACCGCAAGAGAACGAAACTGTGGACACAAAACGCCAAGTATCGCTCTACTATAGCATCCTTTTATGTAGTTTTAAATGGCCATTTTGAATTTTCACATGTAGACGATTCTCTCTATATATGCGTACGGGAGGCTGAATAGTATTCACCTATAGTGTTTCCTTAGTGCTGGTGGGCCGTCCGCTTATATCGGAGACCATGCATATGGACTAGGACTTGTAACAAACGTAACTTGTCGGCCGATCCTTCTGTGTAAAACTTTCATTTTGTATTCGGACCCTTATCCGGTTTGAAGGAGAGGTCGCTCCAGGAAGTATTTTCGCCACGTGACTAGTGTCGTCTGGATTCCCTAATTACCCCACGGTACCTCTAAC"
Acounter = 0
Ccounter = 0
Tcounter = 0
Gcounter = 0
for letter in string:
    if letter == 'A':
        Acounter += 1
    elif letter =='C': 
        Ccounter += 1
    elif letter =='T':
        Tcounter += 1
    elif letter =='G':
        Gcounter += 1

print(f"{Acounter} {Ccounter} {Gcounter} {Tcounter}")